name: CI

on:
  push:
    branches: [ main, staging, production ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: 
      name: ${{ steps.extract_branch.outputs.branch }}
    
    env:
      key: ${{ steps.extract_branch.outputs.branch }}
      
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - uses: actions/checkout@v2
      - name: Run a one-line script
        shell: bash
        run: echo "i'm at $key"
