name: CI

on:
  push:
    branches: [ main, staging, production ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      if: github.ref == 'refs/heads/main'
      env_name: "development"
      
    environment: 
      name: development
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        shell: bash
        run: echo "i'm at d e v e l o p m e n t ${{ env.env_name }} "
