name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_dev:
    runs-on: ubuntu-latest
    environment: 
      name: development
    env:
      key1: ${{ secrets.NEW_KEY }} 
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        if: ${{ env.key1 }} == 'development'
        shell: bash
        run: echo "i'm at d e v e l o p m e n t"
          
  build_stageing:
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    env:
      key1: ${{ secrets.NEW_KEY }} 
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        if: ${{ env.key1 }} == 'xxxxx123'
        shell: bash
        run: echo "i'm at s t a g i n g"
