name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_dev:
    runs-on: ubuntu-latest
    environment: 
      name: development
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        shell: bash
        run: echo "i'm at d e v e l o p m e n t ${{ secrets.NEW_KEY }} "
          
  build_stageing:
    runs-on: ubuntu-latest
    environment: 
      name: Prod
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        shell: bash
        run: echo "i'm at s t a g i n g ${{ secrets.NEW_KEY }} "
