name: CI

on:
  push:
    branches: [ main, staging, production ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: 
      name: ${GITHUB_REF##*/}
    
    env:
      key: ${GITHUB_REF##*/}
      
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script 2
        shell: bash
        run: echo "i'm at ${GITHUB_REF##*/} ${{ secrets.NEW_KEY }}"
